# Global --------------------------

variables:
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
    key: "${CI_JOB_NAME}"
    paths:
        - .cache/pip
        - .venv

stages:
    - quality
    - tests
    - deploy

# Jobs templates ------------------

.install-deps-template: &install-deps
    before_script:
        - pip install poetry
        - poetry --version
        - poetry config virtualenvs.in-project true
        - poetry install -vv

.quality-template: &quality
    <<: *install-deps
    image: python:3.9
    stage: quality

.test-template: &test
    <<: *install-deps
    stage: tests
    coverage: '/TOTAL.*\s(\d+\.\d+\%)/'
    script: poetry run pytest

.deploy-template: &deploy
    <<: *install-deps
    stage: deploy
    script:
        - poetry config repositories.wbc http://pypi.dokku2.woosterbrush.com/
        - poetry config http-basic.wbc zachmyers foobar
        - poetry build
        - poetry publish -r wbc

# Quality jobs ----------------------

check-black:
    <<: *quality
    script: poetry run black --check --config pyproject.toml src/

check-flake8:
    <<: *quality
    script: poetry run flake8 src/ --count --select=E9,F63,F7,F82,F401 --show-source --statistics

# Tests jobs ------------------------

python3.6:
    <<: *test
    image: python:3.6

python3.7:
    <<: *test
    image: python:3.7

python3.8:
    <<: *test
    image: python:3.8

python3.9:
    <<: *test
    image: python:3.9

# Deploy jobs -----------------------

deploy-pypi:
    <<: *deploy
    only:
        - master
