stages:
  - test

test:
  stage: test
  script:
    - python3 -m pip install poetry
    - poetry install --no-root
    - poetry run black --check --config pyproject.toml src/
    - poetry run black --check --config pyproject.toml tests/
    - poetry run flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
    - poetry run flake8 tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
