[tool.black]
line-length = 79
target-version = ['py38']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.poetry]
name = "{{ cookiecutter.project_name }}"
description="{{ cookiecutter.project_short_description }}"
authors=["{{ cookiecutter.full_name }}"]
version = "{{ cookiecutter.version }}"

[tool.poetry.dependencies]
python = ">=3.6,<4.0"
typer = "^0.3.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.8.3"
pytest = "^5.4.3"
bump2version = "^1.0.1"
pyinstaller = "^4.0"

[[tool.poetry.source]]
name = "wbc"
url = "http://pypi.dokku2.woosterbrush.com/"
